// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzccVuCvqzm831-aTpkNrYo_zUo5J_GbI',
    appId: '1:186222395105:web:2955ffa870045e4272c1a0',
    messagingSenderId: '186222395105',
    projectId: 'wxasgn',
    authDomain: 'wxasgn.firebaseapp.com',
    storageBucket: 'wxasgn.firebasestorage.app',
    measurementId: 'G-L3NL0Z62CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfthRxzxtGEU8WThCsb3Gz7iFcf8VqzmY',
    appId: '1:186222395105:android:95c4a7293ae79e3b72c1a0',
    messagingSenderId: '186222395105',
    projectId: 'wxasgn',
    storageBucket: 'wxasgn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2S-IFTMiIopOsfKqIKyz9eKUuy3XYrc',
    appId: '1:186222395105:ios:299a70a0d59f068b72c1a0',
    messagingSenderId: '186222395105',
    projectId: 'wxasgn',
    storageBucket: 'wxasgn.firebasestorage.app',
    iosBundleId: 'com.example.wx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2S-IFTMiIopOsfKqIKyz9eKUuy3XYrc',
    appId: '1:186222395105:ios:299a70a0d59f068b72c1a0',
    messagingSenderId: '186222395105',
    projectId: 'wxasgn',
    storageBucket: 'wxasgn.firebasestorage.app',
    iosBundleId: 'com.example.wx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzccVuCvqzm831-aTpkNrYo_zUo5J_GbI',
    appId: '1:186222395105:web:6449492bfb5ada6b72c1a0',
    messagingSenderId: '186222395105',
    projectId: 'wxasgn',
    authDomain: 'wxasgn.firebaseapp.com',
    storageBucket: 'wxasgn.firebasestorage.app',
    measurementId: 'G-8MLYKFESQS',
  );
}
